

module BNFC.AbsApertium where

-- Haskell module generated by the BNF converter




newtype Punct = Punct String deriving (Eq,Ord,Show,Read)
newtype Iden = Iden String deriving (Eq,Ord,Show,Read)
data Text =
   Lines [Line]
  deriving (Eq,Ord,Show,Read)

data Line =
   Line Iden [Analysis]
 | LinePunct Punct
 | NoAnalysis Iden Iden
  deriving (Eq,Ord,Show,Read)

data Analysis =
   Anal Iden [TagA]
  deriving (Eq,Ord,Show,Read)

data TagA =
   TagA Iden
  deriving (Eq,Ord,Show,Read)

