all:
	pdflatex lrec2016_listenmaa_claessen.tex
	bibtex lrec2016_listenmaa_claessen
	pdflatex lrec2016_listenmaa_claessen.tex
	pdflatex lrec2016_listenmaa_claessen.tex

clean:
	rm *.aux *.log *.dvi *.fdb_latexmk *.bbl *.toc *.fls
